# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('categorias', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Cerdo'), (1, 'Chino'), (2, 'Completos'), (3, 'Egipcio'), (4, 'Empanadas'), (5, 'Ensalada'), (6, 'Japones'), (7, 'Pan'), (8, 'Papas fritas'), (9, 'Pasta'), (10, 'Pescado'), (11, 'Pollo'), (12, 'Postres'), (13, 'Sushi'), (14, 'Vacuno'), (15, 'Vegano'), (16, 'Vegetariano')], max_length=40)),
                ('descripcion', models.CharField(max_length=500)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('precio', models.PositiveSmallIntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='productos')),
            ],
            options={
                'db_table': 'Comida',
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(default='2017-06-25', max_length=200)),
            ],
            options={
                'db_table': 'Favoritos',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='avatars')),
            ],
            options={
                'db_table': 'imagen',
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('idTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('fecha', models.CharField(default='2017-06-25', max_length=200)),
                ('comida', models.ManyToManyField(blank=True, to='main.Comida')),
            ],
            options={
                'db_table': 'transacciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('tipo', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Usuario')),
            ],
            options={
                'db_table': 'admin',
            },
            bases=('main.usuario',),
        ),
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Usuario')),
            ],
            options={
                'db_table': 'alumno',
            },
            bases=('main.usuario',),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Usuario')),
                ('formasDePago', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Efectivo'), (1, 'Tarjeta de Crédito'), (2, 'Tarjeta de Débito'), (3, 'Tarjeta Junaeb')], max_length=7, null=True)),
                ('longitud', models.DecimalField(decimal_places=6, default=-33.457879, max_digits=8)),
                ('latitud', models.DecimalField(decimal_places=6, default=-70.663949, max_digits=8)),
            ],
            options={
                'db_table': 'vendedor',
            },
            bases=('main.usuario',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comida',
            name='idVendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.CreateModel(
            name='vendedorAmbulante',
            fields=[
                ('vendedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Vendedor')),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'vendedorAmbulante',
            },
            bases=('main.vendedor',),
        ),
        migrations.CreateModel(
            name='vendedorFijo',
            fields=[
                ('vendedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Vendedor')),
                ('horarioIni', models.CharField(blank=True, max_length=200, null=True)),
                ('horarioFin', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'vendedorFijo',
            },
            bases=('main.vendedor',),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='idVendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Vendedor'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='idAlumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alumno'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='idVendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vendedor'),
        ),
    ]
