# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertapolicial',
            name='idAlumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
    ]
