# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
