# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha',
            field=models.CharField(default='2017-06-24', max_length=200),
        ),
    ]
