# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170623_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedorambulante',
            name='activo',
            field=models.BooleanField(),
        ),
    ]
