# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170626_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=-33.457879, max_digits=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=-70.663949, max_digits=8),
        ),
    ]
