# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170626_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertapolicial',
            name='fecha',
            field=models.CharField(default='20:42:49.835295+00:00', max_length=200),
        ),
    ]
