# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alertapolicial_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertapolicial',
            name='fecha',
            field=models.CharField(default='442498+00:00', max_length=200),
        ),
    ]
