# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170626_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertapolicial',
            name='fecha',
            field=models.CharField(default='2017-06-26 20:45:08.366114+00:00', max_length=200),
        ),
    ]
