# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170626_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertapolicial',
            name='hora',
            field=models.CharField(default='20:50', max_length=200),
        ),
        migrations.AlterField(
            model_name='alertapolicial',
            name='fecha',
            field=models.CharField(default='2017-06-26', max_length=200),
        ),
    ]
