# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170626_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertapolicial',
            name='hora',
            field=models.CharField(default='23:59', max_length=200),
        ),
        migrations.AlterField(
            model_name='comida',
            name='idVendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vendedor'),
        ),
    ]
